- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: Please enter user name
    private: false

  - name: password
    prompt: Please enter password
    private: true
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "Username is : {{username}}, password is : {{password}}"
