- name: ansisble conditions
  hosts: local
  connection: local
  vars:
    IS_LIVEE: true
  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "Yes, it is live"
    when: IS_LIVE
