- name: ansible install packages demo
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - mysql
    - nginx
    - zip
