- name: ansible error handling demo
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: id_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ id_output }}"

  - name: create user
    ansible.builtin.command: useradd roboshop # to create the roboshop user
    when: id_output.rc !=0 # rc -> return code
